<?php

use Illuminate\Database\Seeder;

class LocDistrictsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('loc_districts')->delete();
        
        \DB::table('loc_districts')->insert(array (
            0 => 
            array (
                'id' => 1,
                'loc_division_id' => 1,
                'division_bbs_code' => '10',
                'title_en' => 'BARGUNA',
                'title' => 'বরগুনা',
                'bbs_code' => '04',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            1 => 
            array (
                'id' => 2,
                'loc_division_id' => 1,
                'division_bbs_code' => '10',
                'title_en' => 'BARISAL',
                'title' => 'বরিশাল',
                'bbs_code' => '06',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            2 => 
            array (
                'id' => 3,
                'loc_division_id' => 1,
                'division_bbs_code' => '10',
                'title_en' => 'BHOLA',
                'title' => 'ভোলা',
                'bbs_code' => '09',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            3 => 
            array (
                'id' => 4,
                'loc_division_id' => 1,
                'division_bbs_code' => '10',
                'title_en' => 'JHALOKATI',
                'title' => 'ঝালকাঠি',
                'bbs_code' => '42',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            4 => 
            array (
                'id' => 5,
                'loc_division_id' => 1,
                'division_bbs_code' => '10',
                'title_en' => 'PATUAKHALI',
                'title' => 'পটুয়াখালী ',
                'bbs_code' => '78',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            5 => 
            array (
                'id' => 6,
                'loc_division_id' => 1,
                'division_bbs_code' => '10',
                'title_en' => 'PIROJPUR',
                'title' => 'পিরোজপুর ',
                'bbs_code' => '79',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            6 => 
            array (
                'id' => 7,
                'loc_division_id' => 2,
                'division_bbs_code' => '20',
                'title_en' => 'BANDARBAN',
                'title' => 'বান্দরবান',
                'bbs_code' => '03',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            7 => 
            array (
                'id' => 8,
                'loc_division_id' => 2,
                'division_bbs_code' => '20',
                'title_en' => 'BRAHMANBARIA',
                'title' => 'ব্রাহ্মণবাড়িয়া',
                'bbs_code' => '12',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            8 => 
            array (
                'id' => 9,
                'loc_division_id' => 2,
                'division_bbs_code' => '20',
                'title_en' => 'CHANDPUR',
                'title' => 'চাঁদপুর',
                'bbs_code' => '13',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            9 => 
            array (
                'id' => 10,
                'loc_division_id' => 2,
                'division_bbs_code' => '20',
                'title_en' => 'CHITTAGONG',
                'title' => 'চট্টগ্রাম',
                'bbs_code' => '15',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            10 => 
            array (
                'id' => 11,
                'loc_division_id' => 2,
                'division_bbs_code' => '20',
                'title_en' => 'COMILLA',
                'title' => 'কুমিল্লা',
                'bbs_code' => '19',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            11 => 
            array (
                'id' => 12,
                'loc_division_id' => 2,
                'division_bbs_code' => '20',
                'title_en' => 'COX\'S BAZAR',
                'title' => 'কক্সবাজার ',
                'bbs_code' => '22',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            12 => 
            array (
                'id' => 13,
                'loc_division_id' => 2,
                'division_bbs_code' => '20',
                'title_en' => 'FENI',
                'title' => 'ফেনী',
                'bbs_code' => '30',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            13 => 
            array (
                'id' => 14,
                'loc_division_id' => 2,
                'division_bbs_code' => '20',
                'title_en' => 'KHAGRACHHARI',
                'title' => 'খাগড়াছড়ি',
                'bbs_code' => '46',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            14 => 
            array (
                'id' => 15,
                'loc_division_id' => 2,
                'division_bbs_code' => '20',
                'title_en' => 'LAKSHMIPUR',
                'title' => 'লক্ষ্মীপুর',
                'bbs_code' => '51',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            15 => 
            array (
                'id' => 16,
                'loc_division_id' => 2,
                'division_bbs_code' => '20',
                'title_en' => 'NOAKHALI',
                'title' => 'নোয়াখালী',
                'bbs_code' => '75',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            16 => 
            array (
                'id' => 17,
                'loc_division_id' => 2,
                'division_bbs_code' => '20',
                'title_en' => 'RANGAMATI',
                'title' => 'রাঙ্গামাটি',
                'bbs_code' => '84',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            17 => 
            array (
                'id' => 18,
                'loc_division_id' => 3,
                'division_bbs_code' => '30',
                'title_en' => 'DHAKA',
                'title' => 'ঢাকা ',
                'bbs_code' => '26',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            18 => 
            array (
                'id' => 19,
                'loc_division_id' => 3,
                'division_bbs_code' => '30',
                'title_en' => 'FARIDPUR',
                'title' => 'ফরিদপুর ',
                'bbs_code' => '29',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            19 => 
            array (
                'id' => 20,
                'loc_division_id' => 3,
                'division_bbs_code' => '30',
                'title_en' => 'GAZIPUR',
                'title' => 'গাজীপুর ',
                'bbs_code' => '33',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            20 => 
            array (
                'id' => 21,
                'loc_division_id' => 3,
                'division_bbs_code' => '30',
                'title_en' => 'GOPALGANJ',
                'title' => 'গোপালগঞ্জ',
                'bbs_code' => '35',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            21 => 
            array (
                'id' => 22,
                'loc_division_id' => 9,
                'division_bbs_code' => '45',
                'title_en' => 'JAMALPUR',
                'title' => 'জামালপুর ',
                'bbs_code' => '39',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '2016-02-09 14:08:46',
            ),
            22 => 
            array (
                'id' => 23,
                'loc_division_id' => 3,
                'division_bbs_code' => '30',
                'title_en' => 'KISHOREGONJ',
                'title' => 'কিশোরগঞ্জ ',
                'bbs_code' => '48',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            23 => 
            array (
                'id' => 24,
                'loc_division_id' => 3,
                'division_bbs_code' => '30',
                'title_en' => 'MADARIPUR',
                'title' => 'মাদারীপুর ',
                'bbs_code' => '54',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            24 => 
            array (
                'id' => 25,
                'loc_division_id' => 3,
                'division_bbs_code' => '30',
                'title_en' => 'MANIKGANJ',
                'title' => 'মানিকগঞ্জ ',
                'bbs_code' => '56',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            25 => 
            array (
                'id' => 26,
                'loc_division_id' => 3,
                'division_bbs_code' => '30',
                'title_en' => 'MUNSHIGANJ',
                'title' => 'মুন্সিগঞ্জ ',
                'bbs_code' => '59',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            26 => 
            array (
                'id' => 27,
                'loc_division_id' => 9,
                'division_bbs_code' => '45',
                'title_en' => 'MYMENSINGH',
                'title' => 'ময়মনসিংহ ',
                'bbs_code' => '61',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '2016-02-09 19:32:20',
            ),
            27 => 
            array (
                'id' => 28,
                'loc_division_id' => 3,
                'division_bbs_code' => '30',
                'title_en' => 'NARAYANGANJ',
                'title' => 'নারায়ণগঞ্জ ',
                'bbs_code' => '67',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            28 => 
            array (
                'id' => 29,
                'loc_division_id' => 3,
                'division_bbs_code' => '30',
                'title_en' => 'NARSINGDI',
                'title' => 'নরসিংদী ',
                'bbs_code' => '68',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            29 => 
            array (
                'id' => 30,
                'loc_division_id' => 9,
                'division_bbs_code' => '45',
                'title_en' => 'NETRAKONA',
                'title' => 'নেত্রকোণা ',
                'bbs_code' => '72',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '2016-02-09 19:31:29',
            ),
            30 => 
            array (
                'id' => 31,
                'loc_division_id' => 3,
                'division_bbs_code' => '30',
                'title_en' => 'RAJBARI',
                'title' => 'রাজবাড়ী ',
                'bbs_code' => '82',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            31 => 
            array (
                'id' => 32,
                'loc_division_id' => 3,
                'division_bbs_code' => '30',
                'title_en' => 'SHARIATPUR',
                'title' => 'শরীয়তপুর  ',
                'bbs_code' => '86',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            32 => 
            array (
                'id' => 33,
                'loc_division_id' => 9,
                'division_bbs_code' => '45',
                'title_en' => 'SHERPUR',
                'title' => 'শেরপুর ',
                'bbs_code' => '89',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '2016-02-09 19:31:55',
            ),
            33 => 
            array (
                'id' => 34,
                'loc_division_id' => 3,
                'division_bbs_code' => '30',
                'title_en' => 'TANGAIL',
                'title' => 'টাঙ্গাইল ',
                'bbs_code' => '93',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            34 => 
            array (
                'id' => 35,
                'loc_division_id' => 4,
                'division_bbs_code' => '40',
                'title_en' => 'BAGERHAT',
                'title' => 'বাগেরহাট',
                'bbs_code' => '01',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            35 => 
            array (
                'id' => 36,
                'loc_division_id' => 4,
                'division_bbs_code' => '40',
                'title_en' => 'CHUADANGA',
                'title' => 'চুয়াডাঙ্গা ',
                'bbs_code' => '18',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            36 => 
            array (
                'id' => 37,
                'loc_division_id' => 4,
                'division_bbs_code' => '40',
                'title_en' => 'JESSORE',
                'title' => 'যশোর ',
                'bbs_code' => '41',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            37 => 
            array (
                'id' => 38,
                'loc_division_id' => 4,
                'division_bbs_code' => '40',
                'title_en' => 'JHENAIDAH',
                'title' => 'ঝিনাইদহ ',
                'bbs_code' => '44',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            38 => 
            array (
                'id' => 39,
                'loc_division_id' => 4,
                'division_bbs_code' => '40',
                'title_en' => 'KHULNA',
                'title' => 'খুলনা ',
                'bbs_code' => '47',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            39 => 
            array (
                'id' => 40,
                'loc_division_id' => 4,
                'division_bbs_code' => '40',
                'title_en' => 'KUSHTIA',
                'title' => 'কুষ্টিয়া ',
                'bbs_code' => '50',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            40 => 
            array (
                'id' => 41,
                'loc_division_id' => 4,
                'division_bbs_code' => '40',
                'title_en' => 'MAGURA',
                'title' => 'মাগুরা',
                'bbs_code' => '55',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            41 => 
            array (
                'id' => 42,
                'loc_division_id' => 4,
                'division_bbs_code' => '40',
                'title_en' => 'MEHERPUR',
                'title' => 'মেহেরপুর ',
                'bbs_code' => '57',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            42 => 
            array (
                'id' => 43,
                'loc_division_id' => 4,
                'division_bbs_code' => '40',
                'title_en' => 'NARAIL',
                'title' => 'নড়াইল ',
                'bbs_code' => '65',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            43 => 
            array (
                'id' => 44,
                'loc_division_id' => 4,
                'division_bbs_code' => '40',
                'title_en' => 'SATKHIRA',
                'title' => 'সাতক্ষীরা ',
                'bbs_code' => '87',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            44 => 
            array (
                'id' => 45,
                'loc_division_id' => 5,
                'division_bbs_code' => '50',
                'title_en' => 'BOGRA',
                'title' => 'বগুড়া ',
                'bbs_code' => '10',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            45 => 
            array (
                'id' => 46,
                'loc_division_id' => 5,
                'division_bbs_code' => '50',
                'title_en' => 'JOYPURHAT',
                'title' => 'জয়পুরহাট',
                'bbs_code' => '38',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            46 => 
            array (
                'id' => 47,
                'loc_division_id' => 5,
                'division_bbs_code' => '50',
                'title_en' => 'NAOGAON',
                'title' => 'নওগাঁ ',
                'bbs_code' => '64',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            47 => 
            array (
                'id' => 48,
                'loc_division_id' => 5,
                'division_bbs_code' => '50',
                'title_en' => 'NATORE',
                'title' => 'নাটোর ',
                'bbs_code' => '69',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            48 => 
            array (
                'id' => 49,
                'loc_division_id' => 5,
                'division_bbs_code' => '50',
                'title_en' => 'CHAPAI NABABGANJ',
                'title' => 'চাঁপাই নাবাবগঞ্জ ',
                'bbs_code' => '70',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            49 => 
            array (
                'id' => 50,
                'loc_division_id' => 5,
                'division_bbs_code' => '50',
                'title_en' => 'PABNA',
                'title' => 'পাবনা',
                'bbs_code' => '76',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            50 => 
            array (
                'id' => 51,
                'loc_division_id' => 5,
                'division_bbs_code' => '50',
                'title_en' => 'RAJSHAHI',
                'title' => 'রাজশাহী ',
                'bbs_code' => '81',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            51 => 
            array (
                'id' => 52,
                'loc_division_id' => 5,
                'division_bbs_code' => '50',
                'title_en' => 'SIRAJGANJ',
                'title' => 'সিরাজগঞ্জ',
                'bbs_code' => '88',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            52 => 
            array (
                'id' => 53,
                'loc_division_id' => 6,
                'division_bbs_code' => '60',
                'title_en' => 'DINAJPUR',
                'title' => 'দিনাজপুর ',
                'bbs_code' => '27',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            53 => 
            array (
                'id' => 54,
                'loc_division_id' => 6,
                'division_bbs_code' => '60',
                'title_en' => 'GAIBANDHA',
                'title' => 'গাইবান্ধা ',
                'bbs_code' => '32',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            54 => 
            array (
                'id' => 55,
                'loc_division_id' => 6,
                'division_bbs_code' => '60',
                'title_en' => 'KURIGRAM',
                'title' => 'কুড়িগ্রাম ',
                'bbs_code' => '49',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            55 => 
            array (
                'id' => 56,
                'loc_division_id' => 6,
                'division_bbs_code' => '60',
                'title_en' => 'LALMONIRHAT',
                'title' => 'লালমনিরহাট ',
                'bbs_code' => '52',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            56 => 
            array (
                'id' => 57,
                'loc_division_id' => 6,
                'division_bbs_code' => '60',
                'title_en' => 'NILPHAMARI',
                'title' => 'নীলফামারী',
                'bbs_code' => '73',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            57 => 
            array (
                'id' => 58,
                'loc_division_id' => 6,
                'division_bbs_code' => '60',
                'title_en' => 'PANCHAGARH',
                'title' => 'পঞ্চগড় ',
                'bbs_code' => '77',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            58 => 
            array (
                'id' => 59,
                'loc_division_id' => 6,
                'division_bbs_code' => '60',
                'title_en' => 'RANGPUR',
                'title' => 'রংপুর ',
                'bbs_code' => '85',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            59 => 
            array (
                'id' => 60,
                'loc_division_id' => 6,
                'division_bbs_code' => '60',
                'title_en' => 'THAKURGAON',
                'title' => 'ঠাকুরগাঁও',
                'bbs_code' => '94',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            60 => 
            array (
                'id' => 61,
                'loc_division_id' => 7,
                'division_bbs_code' => '70',
                'title_en' => 'HABIGANJ',
                'title' => 'হবিগঞ্জ ',
                'bbs_code' => '36',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            61 => 
            array (
                'id' => 62,
                'loc_division_id' => 7,
                'division_bbs_code' => '70',
                'title_en' => 'MAULVIBAZAR',
                'title' => 'মৌলভীবাজার ',
                'bbs_code' => '58',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            62 => 
            array (
                'id' => 63,
                'loc_division_id' => 7,
                'division_bbs_code' => '70',
                'title_en' => 'SUNAMGANJ',
                'title' => 'সুনামগঞ্জ ',
                'bbs_code' => '90',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            63 => 
            array (
                'id' => 64,
                'loc_division_id' => 7,
                'division_bbs_code' => '70',
                'title_en' => 'SYLHET',
                'title' => 'সিলেট',
                'bbs_code' => '91',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
        ));
        
        
    }
}